import { TbAuthService } from '../auth.service';
import { LoginRequest } from '../models/login-request';
import { AfterContentInit } from '@angular/core';
import { Router } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import * as i0 from "@angular/core";
export declare class TbLoginComponent implements AfterContentInit {
    authService: TbAuthService;
    router: Router;
    private dialog;
    private doc?;
    private cachedCompanies;
    capsLockOn: boolean;
    validate: boolean;
    loading: boolean;
    loginRequest: LoginRequest;
    redirectUrl: string;
    buttonText: string;
    currentYear: string;
    createAccountUrl: string;
    changePasswordUrl: string;
    subscriptionSelection: boolean;
    showSignUp: boolean;
    loginSubscriptions: Array<{
        description: string;
        subscriptionkey: string;
    }>;
    logoURL: string;
    isConnected: boolean;
    document?: Document;
    chooseSubscription: string;
    goodJob: string;
    subscription: string;
    buttonBack: string;
    accountName: string;
    welcome: string;
    enterCredentials: string;
    forgetPassword: string;
    blocMaiusc: string;
    idleTimeoutMessage: string;
    dropDownIsClicked: boolean;
    constructor(authService: TbAuthService, router: Router, dialog: MatDialog, doc?: any);
    ngAfterContentInit(): void;
    checkConnection(): Promise<void>;
    keyUpFunction(event: KeyboardEvent): void;
    disabledButton(): boolean;
    get isExpiredSession(): boolean;
    newUser(): void;
    back(): Promise<void>;
    login(): Promise<void>;
    loadLoginData(): void;
    private saveLoginData;
    getCompaniesForUser(user: string): Promise<void>;
    private requestAndSortSubscriptions;
    private compareCompanies;
    goToForgotPassword(): void;
    forgotpassword(Title: string, Message: string, PlaceHolder: string): Promise<void>;
    isDropDownClicked(): void;
    static ɵfac: i0.ɵɵFactoryDef<TbLoginComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<TbLoginComponent, "tb-login", never, {}, {}, never, never>;
}
